name: diploma
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.5
  - pandas=1.2.0
  - cudatoolkit=11.0.221
  - pytorch=1.7.0
  - torchvision=0.8.1
  - pytorch-lightning=1.0.8
  - pydantic=1.7.3
  - omegaconf=2.0.5
  - hydra-core=1.0.5
  - pip:
      - aim